### ISSUE TITLE
git submodule out of date - macaw-base and flexdis - top level commit missing?

### ISSUE THREAD

**Issue by shapr** [GaloisInc/reopt#10]
git submodules grabs macaw-base-0.0.1, but the cabal file requires macaw-base-0.0.2
I checked out master for all the submodules, more of the code builds, but 
 LoadOptions in Data.Macaw.Memory.LoadCommon has changed field names, it's no longer loadStyle, but now loadStyleOverride. 

I suspect there's a commit missing from the top level repo.

**Comment by joehendrix** [comment]
Thanks for the report.  It should be pushed now.
