### ISSUE TITLE
Bug: comparisons between pointers and the number zero

### ISSUE THREAD

**Issue by Ptival** [GaloisInc/reopt#183]
Example in `date` block `block_0_402be0`:
```
  %t1 = icmp eq i64 %t0, 0
```

Example the other way around in `column` block `block_0_402760`:
```
%t0 = icmp eq { i8, i8 }* %arg0, 0
```

**Comment by simonjwinwood** [comment]
These are allowed (e.g. ```ptr == NULL```)

**Comment by Ptival** [comment]
These are not allowed by LLVM, as the comparison does not operate in a single type. We either need to cast the zero into a pointer, or cast the pointer into an `i64`.
