### ISSUE TITLE
`git submodule update --init` gives "fatal: Could not read from remote repository."

### ISSUE THREAD

**Issue by mewmew** [GaloisInc/reopt#45]
Hi!

Reopt looks like a really interesting project, and I'd love to get the chance to start using it and develop a further understanding of it's inner architecture and design.

I recently tried to build `reopt` on one of my new laptops, and then noticed an issue that is not obvious for already configured development laptops.

The way that the submodules (of dependencies) are currently setup in `reopt` requires you to use a Git SSH key, otherwise, you run into an error when running `git submodule update --init`.

In particular, for all the submodules (e.g. `llvm-pretty-bc-parser`, `macaw`, etc), running `git submodule update --init` gives the error "fatal: Could not read from remote repository. Please make sure you have correct access rights"

This is because all submodules are accessed using `git@github.com:GaloisInc/foo.git` instead of e.g. `https://github.com/GaloisInc/foo.git`.

While a very small issue, it does make it more difficult to get started with the project as a new user. Thus, I wanted to let you know, as this issue is not likely to turn up in the development environment of existing developers.

Cheers,
Robin

**Comment by joehendrix** [comment]
Would prebuilt binaries or containers (e.g. docker images) make trying out reopt easier for you?  I can switch the urls by default for those without Github accounts, but I'm not sure how many people will be served by compiling from source versus us just putting prebuilt images up.

**Comment by mewmew** [comment]
Hi @joehendrix,

Thanks for giving this some thought. I prefer the source build, and have `reopt` working on my development laptop.

This issue was mostly to give a heads up that `git clone --recursive` (and other Git submodule commands) may not work for users that have no configured Git SSH key; which is probably fine. The alternative would be to set the `origin` of submodules to use `https://github.com/org/repo.git` schema instead of `git@github.com:org/repo.git`. The trade-off is whether to make it easier for developers of `reopt` or first time users without Git keys (of which there are likely fewer). Personally, I think it makes more sense to have the experience optimized for developers of `reopt`.

That being said, providing access to e.g. Docker images with re-build environment of `reopt` would certainly be useful for people that want to try out the project without having to configure the build environment. The two are not mutually exclusive :)

Cheers,
Robin

**Comment by joehendrix** [comment]
I'm going to update the readme to address this for now.  I plan to continue making the tool more robust before making it easy for people to run into problems running the tool.

**Comment by mewmew** [comment]
> I'm going to update the readme to address this for now. I plan to continue making the tool more robust before making it easy for people to run into problems running the tool.

Thanks @joehendrix!

On a related note, regarding the robustness of `reopt`, I tried lifting a sample binary the other day but `reopt` failed with an error since the binary contained Control Flow Integrity enforcement instructions; in particular `reopt` did not seem to know how to handle the `ENDBR64` instruction (or `ENDBR32`) of Intel CET (Control-flow Enhancement Technology) [[1]]. Most lifters handle these instructions as `NOP` instructions, as they don't perform any operation except enforcing control-flow restrictions. When lifting to LLVM IR, such restrictions may already be enforced by the language (depending on how indirect branches are modelled).

[1]: https://software.intel.com/sites/default/files/managed/4d/2a/control-flow-enforcement-technology-preview.pdf

**Comment by travitch** [comment]
The CFI instruction support is missing in the disassembler and being tracked in GaloisInc/flexdis86#9. I don't have a timeline but would also like to get to that soon.

**Comment by mewmew** [comment]
Thanks Tristan! Good to know.

**Comment by travitch** [comment]
@mewmew I've added support in the relevant core tools (flexdis86 and macaw) for the endbr instructions.  As you note, they are currently treated as no-ops.  This support is enough for many cases, but I've noticed that some newer compilers are generating a new variant of indirect jump (the `notrack` prefix, which disables CFI checking for a given jump).  Macaw does not have support for those yet.

**Comment by mewmew** [comment]
Thanks for keeping me updated @travitch! Glad to see support for `endbr` having landed in the disassembler used by reopt. Did not know there was a `notrack` prefix. Hopefully my sample binaries will work now with `endbr`. We'll see!

Cheers,
Robin

**Comment by travitch** [comment]
Just to be clear, I think we still need to update reopt to take advantage of the change - it might just be a matter of updating submodules, but I'm not sure offhand

**Comment by mewmew** [comment]
> Just to be clear, I think we still need to update reopt to take advantage of the change - it might just be a matter of updating submodules, but I'm not sure offhand

Sure. I'll probably give this a try in a week or two. So no rush.
